version: '3.8'

services:
  web:
    build:
      context: ./app          # Build the Flask app from the local directory './app'
      dockerfile: Dockerfile  # Use the Dockerfile located in the 'app' directory
    ports:
      - "5000:5000"           # Expose Flask app on port 5000
    depends_on:
      - redis                 # Ensure Redis starts before the web service

  redis:
    image: "redis:alpine"     # Use the official Redis image from Docker Hub
    ports:
      - "6379:6379"
