version: '3.8'

services:
  web:
    build:
      context: .          # Build the Flask app from the local directory
      dockerfile: Dockerfile  # Use the Dockerfile located in the 'my_flask' directory
    ports:
      - "5002:5002"           # Expose Flask app on port 5002
    depends_on:
      - redis                 # Ensure Redis starts before the web service

  redis:
    image: "redis:alpine"     # Use the official Redis image from Docker Hub
    ports:
      - "6379:6379"
